services:
  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./shared:/shared
    command: sh -c "if [ ! -d node_modules ]; then npm install; fi && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./shared:/shared
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true
