services:
  backend:
    networks:
      - routine-net
    environment:
      - TZ=Europe/Athens

  frontend:
    depends_on:
      - backend
    networks:
      - routine-net

networks:
  routine-net:
