services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/data
    environment:
      - DATA_FILE=/data/data.json
      - STATE_FILE=/data/state.json
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always